### ISSUE TITLE
Unable to modify existing session

### ISSUE THREAD

**Issue by keidrych** [jsumners/fastify-server-session#7] opened 2019-03-27 13:34 UTC
With the recent re-factoring this seems to have broken: 

Always able to reproduce.
1. Create a new server session, everything works as expected
2. Modify an existing server session, failure resulting in 'cache' in this.cache missing in the onSend hook.

Calling /one twice will cause the failure irrespective of what values are being placed in the session object.

```
"use strict";

require("make-promises-safe").abort = true;

const abcache = require("abstract-cache")({
  useAwait: false // Required for fastify-server-session to function correctly
});

const fastify = require("fastify")({ logger: true });

fastify
  .register(require("fastify-cookie"))
  .register(require("fastify-caching"), { cache: abcache })
  .register(require("fastify-server-session"), {
    secretKey: "TIJABylXmL0tlQgyXd3RnCexkj6jbRO4",
    sessionMaxAge: 900000
  })
  .register(require("fastify-sensible"))
  .register(require("fastify-blipp"));

// Routes
fastify.get("/one", (req, reply) => {
  req.session.foo = "foo";
  reply.send();
});

fastify.get("/two", (req, reply) => {
  req.session.redux = "bleh";
  reply.send({ foo: req.session });
});
// Ensure Errors are easily available for Fastify Sensible
global.httpErrors = fastify.httpErrors;

fastify.listen(3000, "0.0.0.0", (err, address) => {
  if (err) {
    throw err;
  }

  fastify.blipp();
  fastify.log.info(`server listening on ${address}`);
});
```

**Comment by mandaputtra** [comment] 2019-03-29 15:50
```
(node:5004) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'cache' of undefined
    at storeSession (D:\Latihan\vf-cms\server\node_modules\fastify-server-session\plugin.js:87:12)
    at Object.<anonymous> (D:\Latihan\vf-cms\server\node_modules\fastify-server-session\plugin.js:71:14)
    at next (D:\Latihan\vf-cms\server\node_modules\fastify\lib\hooks.js:105:34)
    at Object.etagOnSend (D:\Latihan\vf-cms\server\node_modules\fastify-caching\plugin.js:44:39)
    at next (D:\Latihan\vf-cms\server\node_modules\fastify\lib\hooks.js:105:34)
    at onSendHookRunner (D:\Latihan\vf-cms\server\node_modules\fastify\lib\hooks.js:119:3)
    at onSendHook (D:\Latihan\vf-cms\server\node_modules\fastify\lib\reply.js:253:5)
    at handleError (D:\Latihan\vf-cms\server\node_modules\fastify\lib\reply.js:418:5)
    at onErrorHook (D:\Latihan\vf-cms\server\node_modules\fastify\lib\reply.js:373:5)
    at _Reply.Reply.send (D:\Latihan\vf-cms\server\node_modules\fastify\lib\reply.js:98:5)
    at defaultErrorHandler (D:\Latihan\vf-cms\server\node_modules\fastify\fastify.js:884:9)
    at handleError (D:\Latihan\vf-cms\server\node_modules\fastify\lib\reply.js:401:18)
    at onErrorHook (D:\Latihan\vf-cms\server\node_modules\fastify\lib\reply.js:373:5)
    at _Reply.Reply.send (D:\Latihan\vf-cms\server\node_modules\fastify\lib\reply.js:98:5)
    at D:\Latihan\vf-cms\server\node_modules\fastify\lib\wrapThenable.js:43:11
```

are this related? 

```
if (pass) {
    const secret = req.generateSecretCSRF
    const tokenCSRF = reply.createTokenCSRF(secret)
    const token = this.jwt.sign({
      userId: user._id,
      role: user.role,
      tokenCSRF,
    })
    user.password = ''

    // generate session secret for crsf
    req.session.scrt = secret
    reply
      .setCookie('tks', token, {
        path: '/'
      })
      .code(200)
      .send({data: user})
  } else {
    reply.code(401).send('your email or password wrong!')
  }
```

Im unable to hit login route twice. and sends 'cache' undefined

[EDIT]

```
if (!req.session.scrt) {
      req.session.scrt = secret
    }
```

just wrapping around like this fixed my issue. but i think this is still bugs because i had to modify my sessions every request.

**Comment by mandaputtra** [comment] 2019-03-29 15:51
And one question again how to destroy sessions?

**Comment by jsumners** [comment] 2019-03-29 17:24
Please refrain from adding off-topic questions to existing threads. Start a new issue if you have something separate.

**Comment by jsumners** [comment] 2019-03-30 12:24
Issue is caused by https://github.com/jsumners/fastify-server-session/blob/5638f3de9e2a9c31b0691133a265c2cef58270a2/plugin.js#L71

Patch incoming.

**Comment by jsumners** [comment] 2019-03-30 12:34
Fixed in https://github.com/jsumners/fastify-server-session/releases/tag/v3.0.1

@Keidrych thank you for the clear bug report with a reproduction included.

@mandaputtra yes, the error you saw was due to the same thing. As for you question: just set the session to `{}`.

**Closed as completed** 2019-03-30 12:34 UTC
Labels: bug
